# Gruvbox Dark colors
set $bg        #282828
set $bg-alt    #3c3836
set $fg        #ebdbb2
set $fg-dim    #a89984

set $red       #cc241d
set $green     #b8bb26
set $yellow    #fabd2f
set $blue      #458588
set $purple    #d3869b
set $aqua      #83a598
set $gray      #928374


# Window colors
client.focused          $yellow   $yellow   $bg      $yellow   $yellow
client.focused_inactive $bg-alt   $bg-alt   $fg-dim  $gray     $bg-alt
client.unfocused        $bg        $bg        $fg-dim  $gray     $bg
client.urgent           $red       $red       $fg      $red     $red
client.placeholder      $bg        $bg        $fg      $bg      $bg


#bar {
#	status_command i3status
#  	status_command i3blocks
# 	position top
# 	tray_output DP-0
#	tray_padding 6
# 	mode dock
# 	hidden_state hide
#     	modifier Mod4
#     colors {
#         background $bg
#         statusline $fg
#         separator  $gray
#         focused_workspace  $yellow $yellow $bg
#         active_workspace   $blue   $bg-alt $fg
#         inactive_workspace $bg     $bg     $fg-dim
#         urgent_workspace   $red    $red    $fg
#         binding_mode       $purple $purple $bg
#     }    
# }
