# Theme - any one
include-file = ~/.config/polybar/themes/gruvbox.ini
#include-file = ~/.config/polybar/themes/winxp_luna.ini
#include-file = ~/.config/polybar/themes/nord.ini


include-file = ~/.config/polybar/modules/systray.ini
include-file = ~/.config/polybar/modules/netspeed.ini
include-file = ~/.config/polybar/modules/xworkspaces.ini
include-file = ~/.config/polybar/modules/xwindow.ini
include-file = ~/.config/polybar/modules/filesystem.ini
include-file = ~/.config/polybar/modules/pulseaudio.ini
include-file = ~/.config/polybar/modules/xkeyboard.ini
include-file = ~/.config/polybar/modules/battery.ini
include-file = ~/.config/polybar/modules/mpris.ini
include-file = ~/.config/polybar/modules/memory.ini
include-file = ~/.config/polybar/modules/network-base.ini
include-file = ~/.config/polybar/modules/eth.ini
include-file = ~/.config/polybar/modules/date.ini
include-file = ~/.config/polybar/modules/bar.ini
include-file = ~/.config/polybar/modules/i3-layout-single.ini
include-file = ~/.config/polybar/modules/tasklist.ini
include-file = ~/.config/polybar/modules/tasks.ini
include-file = ~/.config/polybar/modules/bluetooth.ini
include-file = ~/.config/polybar/modules/current-audio-device.ini
include-file = ~/.config/polybar/modules/screenrecord.ini
include-file = ~/.config/polybar/modules/tray-toggle.ini



[settings]
screenchange-reload = true
pseudo-transparency = true
