set $MONITOR_1 "DP-4"
set $MONITOR_1_REFRESH_RATE "143.98"
set $MONITOR_1_SCREEN_RESOLUTION "1920x1080"

set $MONITOR_2 "DP-0"
set $MONITOR_2_REFRESH_RATE "239.76"
set $MONITOR_2_SCREEN_RESOLUTION "1920x1080"


#Set screen resolution
set $MONITOR_2 "DP-0"
set $MONITOR_2_REFRESH_RATE "239.76"
set $MONITOR_2_SCREEN_RESOLUTION "1920x1080"

exec_always --no-startup-id xrandr --output $MONITOR_1 --mode $MONITOR_1_SCREEN_RESOLUTION --rate $MONITOR_1_REFRESH_RATE
exec_always --no-startup-id xrandr --output $MONITOR_2 --mode $MONITOR_2_SCREEN_RESOLUTION --rate $MONITOR_2_REFRESH_RATE
