#font pango:monospace 16
#font pango:DejaVu Sans Mono 14
#font pango:JetBrainsMono Nerd Font 14
#font pango:IBM Plex Mono 14
#font pango:Terminus 14
font pango:Iosevka 14


# Remove titlebars — set border style to pixel (1px border) or none
default_border pixel 1
default_floating_border pixel 1

# Also handle any legacy setting
for_window [class=".*"] border pixel 1

# Gaps between windows - looks cool
gaps inner 10
gaps outer 0
smart_gaps off
