# Polybar
exec_always --no-startup-id ~/.config/polybar/launch.sh

# Start XDG autostart .desktop files using dex. See also
# https://wiki.archlinux.org/index.php/XDG_Autostart
exec --no-startup-id dex --autostart --environment i3

# Import variables into the systemd and D-Bus user session
exec --no-startup-id dbus-update-activation-environment --systemd DISPLAY XAUTHORITY

# Ensure the portal service restarts with the fresh environment
exec --no-startup-id systemctl --user restart xdg-desktop-portal

# Compositor for transparency and shadows
exec --no-startup-id picom

#polkit session -> Authorisation popups where you enter your password for authentication
# Below works for arch, install polkit-gnome
exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1


# No screen blanking - I want my system to always on, no sleep no lockscreen - install xorg-xset package
exec --no-startup-id xset s off -dpms

# XDG desktop portal for proper GTK dialogs and sandboxed apps
#exec --no-startup-id /usr/lib/xdg-desktop-portal-gtk

# Set wallpaper at startup
exec --no-startup-id feh --randomize --bg-fill $WALLPAPER_DIR

# NetworkManager is the most popular way to manage wireless networks on Linux,
# and nm-applet is a desktop environment-independent system tray GUI for it.
# Install network-manager-applet in arch
exec --no-startup-id dbus-launch nm-applet

# Notification daemon
exec --no-startup-id dunst

exec --no-startup-id dbus-run-session i3

exec --no-startup-id mpd

# Auto start gnome keyring so it wont ask again and again - eg. starting Brave Browser
exec --no-startup-id /usr/bin/gnome-keyring-daemon --start --components=ssh,secrets,pkcs11


exec --no-startup-id blueman-applet

