# Notes picker floating window center
for_window [title="notes-picker"] floating enable, resize set 900 600, move position center
for_window [title="notes-new"]   floating enable, resize set 1200 800, move position center






