# Windows XP (Luna / Classic–inspired) colors
set $bg        #ECE9D8
set $bg-alt    #D4D0C8
set $fg        #000000
set $fg-dim    #404040

set $red       #C00000
set $green     #008000
set $yellow    #F5DB95
set $blue      #0054E3
set $purple    #800080
set $aqua      #008080
set $gray      #808080


# Window colors (XP-style)
client.focused          $blue     $blue     $fg      $yellow   $blue
client.focused_inactive $bg-alt   $bg-alt   $fg-dim  $gray     $bg-alt
client.unfocused        $bg       $bg       $fg-dim  $gray     $bg
client.urgent           $red      $red      $fg      $red     $red
client.placeholder      $bg       $bg       $fg      $bg      $bg
