# Theme - any one
include-file = ~/.config/polybar/themes/gruvbox.ini
#include-file = ~/.config/polybar/themes/nord.ini

include-file = ~/.config/polybar/font.ini
include-file = ~/.config/polybar/modules/pulseaudio.ini
include-file = ~/.config/polybar/modules/scrcpy_battery.ini
include-file = ~/.config/polybar/modules/screenrecord.ini
include-file = ~/.config/polybar/modules/systray.ini
include-file = ~/.config/polybar/modules/xwindow.ini
include-file = ~/.config/polybar/modules/xworkspaces.ini
include-file = ~/.config/polybar/modules/date.ini
include-file = ~/.config/polybar/modules/launcher.ini
include-file = ~/.config/polybar/modules/battery.ini
include-file = ~/.config/polybar/modules/powerprofile.ini



[settings]
screenchange-reload = true
pseudo-transparency = true

[bar/mainbar]
inherit = bar/fonts
monitor = ${env:MONITOR:}
width = 100%
height = 18pt
radius = 0

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

bottom = false

line-size = 6pt

#border-size = 4pt
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = 
separator-foreground = ${colors.flamingo}

font-1 = "JetBrainsMono Nerd Font:size=12;4"


modules-left = xworkspaces xwindow
modules-right = scrcpy_battery screenrecord pulseaudio systray battery date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; wm-restack = generic
; wm-restack = bspwm
wm-restack = i3

; override-redirect = true





