# Theme - any one
include-file = ~/.config/polybar/themes/gruvbox.ini
#include-file = ~/.config/polybar/themes/nord.ini

include-file = ~/.config/polybar/modules/bar.ini
include-file = ~/.config/polybar/modules/pulseaudio.ini
include-file = ~/.config/polybar/modules/scrcpy_battery.ini
include-file = ~/.config/polybar/modules/screenrecord.ini
include-file = ~/.config/polybar/modules/systray.ini
include-file = ~/.config/polybar/modules/xwindow.ini
include-file = ~/.config/polybar/modules/xworkspaces.ini
include-file = ~/.config/polybar/modules/date.ini
include-file = ~/.config/polybar/modules/launcher.ini
include-file = ~/.config/polybar/modules/battery.ini
include-file = ~/.config/polybar/modules/powerprofile.ini



[settings]
screenchange-reload = true
pseudo-transparency = true



